In [1]:
import pandas as pd

# pd.date_range()

In [2]:
#The pd.date_range() function in pandas is used to generate a sequence of dates (a DatetimeIndex)
#based on specific criteria. It is particularly useful 
#when you need to create a range of dates for time series analysis or when working with date-related data.

In [3]:
'''
start:
The starting date of the sequence.
Example: '2024-01-01'.

end:
The ending date of the sequence.
Example: '2024-01-10'.
periods:

The number of periods (dates) to generate. If specified, either start or end must also be given.
Example: 10.
freq:

The frequency of the dates. It can be a string or DateOffset. Some common options are:
'D' for daily (default)
'H' for hourly
'M' for month-end
'W' for weekly
Example: 'M' (for month-end).
tz:

Time zone name for the resulting DatetimeIndex.
Example: 'Asia/Kolkata'.
normalize:

If True, the start and end dates will be normalized to midnight.
Example: normalize=True.
name:

The name of the resulting DatetimeIndex.
Example: 'date_range'.
closed:

Whether to keep the interval open or closed on one or both ends.
Options: 'left', 'right', or None (default).
inclusive:

Controls whether the interval is inclusive of the start and end points if both are given.
Options: 'both', 'neither', 'left', or 'right'.

'''

"\nstart:\nThe starting date of the sequence.\nExample: '2024-01-01'.\n\nend:\nThe ending date of the sequence.\nExample: '2024-01-10'.\nperiods:\n\nThe number of periods (dates) to generate. If specified, either start or end must also be given.\nExample: 10.\nfreq:\n\nThe frequency of the dates. It can be a string or DateOffset. Some common options are:\n'D' for daily (default)\n'H' for hourly\n'M' for month-end\n'W' for weekly\nExample: 'M' (for month-end).\ntz:\n\nTime zone name for the resulting DatetimeIndex.\nExample: 'Asia/Kolkata'.\nnormalize:\n\nIf True, the start and end dates will be normalized to midnight.\nExample: normalize=True.\nname:\n\nThe name of the resulting DatetimeIndex.\nExample: 'date_range'.\nclosed:\n\nWhether to keep the interval open or closed on one or both ends.\nOptions: 'left', 'right', or None (default).\ninclusive:\n\nControls whether the interval is inclusive of the start and end points if both are given.\nOptions: 'both', 'neither', 'left', or 'right'.\n\n"

In [4]:
pd.date_range(start='2024-01-01', end='2024-01-10')

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D')

In [5]:
pd.date_range(start='2024-01-01', periods=5)

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05'],
              dtype='datetime64[ns]', freq='D')

In [6]:
pd.date_range(start='2024-01-01', end='2024-03-01', freq='W')  # Here W (Weekly) = Sunday - default

DatetimeIndex(['2024-01-07', '2024-01-14', '2024-01-21', '2024-01-28',
               '2024-02-04', '2024-02-11', '2024-02-18', '2024-02-25'],
              dtype='datetime64[ns]', freq='W-SUN')

In [7]:
pd.date_range(start='2024-01-01', end='2024-03-01', freq='W-MON')  ## Here W (Weekly) = Monday -

DatetimeIndex(['2024-01-01', '2024-01-08', '2024-01-15', '2024-01-22',
               '2024-01-29', '2024-02-05', '2024-02-12', '2024-02-19',
               '2024-02-26'],
              dtype='datetime64[ns]', freq='W-MON')

In [8]:
pd.date_range(start='2024-01-01', end='2024-03-01', freq='W-FRI')  ## Here W (Weekly) = Friday -

DatetimeIndex(['2024-01-05', '2024-01-12', '2024-01-19', '2024-01-26',
               '2024-02-02', '2024-02-09', '2024-02-16', '2024-02-23',
               '2024-03-01'],
              dtype='datetime64[ns]', freq='W-FRI')

In [9]:
pd.date_range(start='2024-08-01', end='2024-12-28', freq='ME')

DatetimeIndex(['2024-08-31', '2024-09-30', '2024-10-31', '2024-11-30'], dtype='datetime64[ns]', freq='ME')

In [10]:
pd.date_range(start='2024-01-01 09:00', periods=6, freq='h')

DatetimeIndex(['2024-01-01 09:00:00', '2024-01-01 10:00:00',
               '2024-01-01 11:00:00', '2024-01-01 12:00:00',
               '2024-01-01 13:00:00', '2024-01-01 14:00:00'],
              dtype='datetime64[ns]', freq='h')

In [11]:
pd.date_range(start='2024-01-01', periods=10, freq='D', tz='Asia/Kolkata')
#+05:30:
#Time Zone Offset: The offset from Coordinated Universal Time (UTC).
#+05:30 means that this time is 5 hours and 30 minutes ahead of UTC.
#This offset corresponds to the time zone in India, known as Indian Standard Time (IST).

DatetimeIndex(['2024-01-01 00:00:00+05:30', '2024-01-02 00:00:00+05:30',
               '2024-01-03 00:00:00+05:30', '2024-01-04 00:00:00+05:30',
               '2024-01-05 00:00:00+05:30', '2024-01-06 00:00:00+05:30',
               '2024-01-07 00:00:00+05:30', '2024-01-08 00:00:00+05:30',
               '2024-01-09 00:00:00+05:30', '2024-01-10 00:00:00+05:30'],
              dtype='datetime64[ns, Asia/Kolkata]', freq='D')

In [12]:
import pandas as pd
import numpy as np

# Create an irregular time series DataFrame
data = {'value': np.random.randint(1, 100, 10)}
df = pd.DataFrame(data, index=pd.to_datetime([
    '2024-01-01', '2024-01-04', '2024-01-10', '2024-01-11',
    '2024-01-14', '2024-01-20', '2024-01-21', '2024-01-25',
    '2024-01-27', '2024-01-30']))

# Resample the DataFrame to a daily frequency, filling missing dates
df_resampled = df.resample('D').mean().fillna(0)

#The resample() function in pandas is used to change the frequency of the time series data.

#If your DataFrame df has timestamps as the index and values recorded at irregular intervals, 
#resampling with 'D' will create a new index with every day in the range, even if there was no 
#original data for some of those days.

In [13]:
 np.random.randint(1, 100, 10)

array([59, 76, 19, 39, 37, 29, 85, 83, 26, 97])

In [14]:
df.head()

            value
2024-01-01     15
2024-01-04     18
2024-01-10     97
2024-01-11     65
2024-01-14     23

In [15]:
df.resample('D').mean().head()

            value
2024-01-01   15.0
2024-01-02    NaN
2024-01-03    NaN
2024-01-04   18.0
2024-01-05    NaN

In [16]:
df_resampled.head()

            value
2024-01-01   15.0
2024-01-02    0.0
2024-01-03    0.0
2024-01-04   18.0
2024-01-05    0.0

In [17]:
# Generate a range of business days
business_days = pd.date_range(start='2024-01-01', end='2024-03-01', freq='B')

print(business_days)

#freq='B'
#What It Does:
#Specifies the frequency of the generated dates.
#'B' stands for Business Day Frequency, which means that the generated dates will include only
#business days (i.e., Monday to Friday) and will exclude weekends (Saturdays and Sundays).

# Create a DataFrame with business days as the index
print("===========================================")
df_business = pd.DataFrame(index=business_days)
print(df_business)
print("===========================================")
df_business['sales'] = np.random.randint(100, 1000, len(df_business))

#Note:
#The len(df_business) function actually returns the number of rows in the DataFrame, 
#not the number of columns. If you want to check the number of columns, 
#you can use df_business.shape[1] or len(df_business.columns).

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-08', '2024-01-09', '2024-01-10',
               '2024-01-11', '2024-01-12', '2024-01-15', '2024-01-16',
               '2024-01-17', '2024-01-18', '2024-01-19', '2024-01-22',
               '2024-01-23', '2024-01-24', '2024-01-25', '2024-01-26',
               '2024-01-29', '2024-01-30', '2024-01-31', '2024-02-01',
               '2024-02-02', '2024-02-05', '2024-02-06', '2024-02-07',
               '2024-02-08', '2024-02-09', '2024-02-12', '2024-02-13',
               '2024-02-14', '2024-02-15', '2024-02-16', '2024-02-19',
               '2024-02-20', '2024-02-21', '2024-02-22', '2024-02-23',
               '2024-02-26', '2024-02-27', '2024-02-28', '2024-02-29',
               '2024-03-01'],
              dtype='datetime64[ns]', freq='B')
===========================================
Empty DataFrame
Columns: []
Index: [2024-01-01 00:00:00, 2024-01-02 00:00:00, 2024-01-03 00:00:00, 2024-01-04 00:00:00, 2024-01-05 00:00:00, 2024-01-08 00:00:00, 2024-01-09 00:00:00, 2024-01-10 00:00:00, 2024-01-11 00:00:00, 2024-01-12 00:00:00, 2024-01-15 00:00:00, 2024-01-16 00:00:00, 2024-01-17 00:00:00, 2024-01-18 00:00:00, 2024-01-19 00:00:00, 2024-01-22 00:00:00, 2024-01-23 00:00:00, 2024-01-24 00:00:00, 2024-01-25 00:00:00, 2024-01-26 00:00:00, 2024-01-29 00:00:00, 2024-01-30 00:00:00, 2024-01-31 00:00:00, 2024-02-01 00:00:00, 2024-02-02 00:00:00, 2024-02-05 00:00:00, 2024-02-06 00:00:00, 2024-02-07 00:00:00, 2024-02-08 00:00:00, 2024-02-09 00:00:00, 2024-02-12 00:00:00, 2024-02-13 00:00:00, 2024-02-14 00:00:00, 2024-02-15 00:00:00, 2024-02-16 00:00:00, 2024-02-19 00:00:00, 2024-02-20 00:00:00, 2024-02-21 00:00:00, 2024-02-22 00:00:00, 2024-02-23 00:00:00, 2024-02-26 00:00:00, 2024-02-27 00:00:00, 2024-02-28 00:00:00, 2024-02-29 00:00:00, 2024-03-01 00:00:00]
===========================================

In [18]:
df_business.shape

(45, 1)

In [19]:
np.random.randint(100, 1000, len(df_business))
len(df_business)

45

# Differences between pd.to_datetime(), pd.Timestamp, and pd.date_range()

In [20]:
#pd.to_datetime() is a pandas function used to convert various date/time formats into pandas' DatetimeIndex or Timestamp objects. 
#It can handle strings, lists, or Series of date/time values and convert them into a more usable format.

#pd.to_datetime() is a pandas function used to convert various date/time formats into 
#pandas' DatetimeIndex or Timestamp objects. It can handle strings, lists, or Series of date/time values 
#and convert them into a more usable format.

In [21]:
pd.to_datetime('2024-01-01')

Timestamp('2024-01-01 00:00:00')

In [22]:
pd.to_datetime(['2024-01-01', '2024-02-01', '2024-03-01'])

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64[ns]', freq=None)

In [23]:
import pandas as pd

# Example DataFrame with mixed date formats and invalid entries
data = {'date': ['2024-01-01', '2024-02-30', 'March 3, 2024', 'not_a_date', '2024-04-04']}
df = pd.DataFrame(data)

# Convert to datetime
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Result
print(df)

        date
0 2024-01-01
1        NaT
2        NaT
3        NaT
4 2024-04-04

In [24]:
import pandas as pd

# Step 1: Create a DataFrame with a 'date' column containing mixed formats and invalid entries
data = {
    'date': ['2024-01-01', '2024-02-30', 'March 3, 2024', 'not_a_date', '2024-04-04'],
    'value': [10, 20, 30, 40, 50]  # Another column for context
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Step 2: Convert the 'date' column to datetime, handling errors with 'coerce'
df['date'] = pd.to_datetime(df['date'], errors='coerce')

print("\nDataFrame after applying pd.to_datetime():")
print(df)

# Fill NaT values with a specific date
df['date'] = df['date'].fillna(pd.Timestamp('2024-01-01'))

print("\nDataFrame after filling NaT values:")
print(df)

# Alternatively, you can drop rows with NaT in the 'date' column
# df.dropna(subset=['date'], inplace=True)

# If you want to see the rows where the conversion failed (NaT)
invalid_rows = df[df['date'].isna()]
print("\nRows where conversion failed (NaT):")
print(invalid_rows)

Original DataFrame:
            date  value
0     2024-01-01     10
1     2024-02-30     20
2  March 3, 2024     30
3     not_a_date     40
4     2024-04-04     50

DataFrame after applying pd.to_datetime():
        date  value
0 2024-01-01     10
1        NaT     20
2        NaT     30
3        NaT     40
4 2024-04-04     50

DataFrame after filling NaT values:
        date  value
0 2024-01-01     10
1 2024-01-01     20
2 2024-01-01     30
3 2024-01-01     40
4 2024-04-04     50

Rows where conversion failed (NaT):
Empty DataFrame
Columns: [date, value]
Index: []

In [25]:
# Create a DataFrame with different time zones
df = pd.DataFrame({
    'datetime': pd.to_datetime(['2024-01-01 12:00:00', '2024-01-01 09:00:00', '2024-01-01 21:00:00']),
    'timezone': ['Asia/Kolkata', 'Europe/London', 'US/Eastern']
})
print(len(df))
# Convert all timestamps to UTC
df['datetime'] = df.apply(lambda x: pd.Timestamp(x['datetime'], tz=x['timezone']).tz_convert('UTC'), axis=1)

3

In [26]:
df.head()

                   datetime       timezone
0 2024-01-01 06:30:00+00:00   Asia/Kolkata
1 2024-01-01 09:00:00+00:00  Europe/London
2 2024-01-02 02:00:00+00:00     US/Eastern

In [27]:
# Create a date range and corresponding data
dates = pd.date_range(start='2024-01-01', periods=30, freq='D')
df = pd.DataFrame({'date': dates, 'value': np.random.randint(1, 100, 30)})

# Set the date as the index
df.set_index('date', inplace=True)

# Calculate the 7-day moving average
df['7_day_avg'] = df['value'].rolling(window=7).mean()

In [28]:
# Generate a large date range
dates = pd.date_range(start='2024-01-01', periods=365, freq='D')
df = pd.DataFrame({'date': dates, 'value': np.random.randint(1, 100, 365)})

# Define event dates
event_dates = pd.to_datetime(['2024-02-14', '2024-07-04'])

# Extract data around the events
df_events = df[df['date'].isin(event_dates)]

df

          date  value
0   2024-01-01     24
1   2024-01-02     25
2   2024-01-03     93
3   2024-01-04     73
4   2024-01-05     39
..         ...    ...
360 2024-12-26     21
361 2024-12-27     53
362 2024-12-28     86
363 2024-12-29     15
364 2024-12-30     32

[365 rows x 2 columns]

In [29]:
# Current date range for existing data
current_dates = pd.date_range(start='2024-01-01', periods=30, freq='D')
df = pd.DataFrame({'date': current_dates, 'value': np.random.randint(1, 100, 30)})

# Future date range for predictions
future_dates = pd.date_range(start='2024-01-31', periods=10, freq='D')

# Predict future values (using a simple linear model for illustration)
df_future = pd.DataFrame({'date': future_dates})
df_future['predicted_value'] = np.linspace(df['value'].iloc[-1], df['value'].mean(), len(future_dates))

df.head()

        date  value
0 2024-01-01      7
1 2024-01-02     70
2 2024-01-03      9
3 2024-01-04     67
4 2024-01-05     44

In [30]:
# Create a time series data
dates = pd.date_range(start='2024-01-01', periods=10, freq='D')
df = pd.DataFrame({'date': dates, 'sales': np.random.randint(100, 500, 10)})

# Shift the data to create lagged values
df['lag_1'] = df['sales'].shift(1)
df['lag_2'] = df['sales'].shift(2)

df

        date  sales  lag_1  lag_2
0 2024-01-01    147    NaN    NaN
1 2024-01-02    395  147.0    NaN
2 2024-01-03    224  395.0  147.0
3 2024-01-04    249  224.0  395.0
4 2024-01-05    151  249.0  224.0
5 2024-01-06    397  151.0  249.0
6 2024-01-07    452  397.0  151.0
7 2024-01-08    435  452.0  397.0
8 2024-01-09    337  435.0  452.0
9 2024-01-10    287  337.0  435.0