In [1]:
import pandas as pd

In [2]:
#Problem: Given a DataFrame containing information about employees, filter out the rows where 
#the employee’s age is greater than 30 and their salary is greater than $50,000.

import pandas as pd

# Sample DataFrame
data = {
    'Employee': ['John', 'Alice', 'Bob', 'Carol', 'Eve'],
    'Age': [25, 32, 28, 35, 45],
    'Salary': [48000, 54000, 52000, 58000, 65000]
}

df = pd.DataFrame(data)

# Filtering condition
filtered_df = df[(df['Age'] > 30) & (df['Salary'] > 50000)]

filtered_df

  Employee  Age  Salary
1    Alice   32   54000
3    Carol   35   58000
4      Eve   45   65000

In [3]:
#Problem: For a DataFrame containing sales data, group by the Region and calculate the total sales and average discount per region.

# Sample DataFrame
sales_data = {
    'Region': ['East', 'West', 'East', 'West', 'East', 'West'],
    'Sales': [234, 678, 123, 456, 789, 987],
    'Discount': [10, 20, 15, 10, 5, 25]
}

df = pd.DataFrame(sales_data)

# Grouping by 'Region' and aggregating
grouped_df = df.groupby('Region').agg({'Sales': 'sum', 'Discount': 'mean'})

grouped_df

        Sales   Discount
Region
East     1146  10.000000
West     2121  18.333333

In [4]:
#Problem: Create a pivot table that shows the sum of sales for each Region and Product combination.

# Sample DataFrame
data = {
    'Region': ['East', 'West', 'East', 'West', 'East', 'West'],
    'Product': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Sales': [234, 678, 123, 456, 789, 987]
}

df = pd.DataFrame(data)

# Creating pivot table
pivot_table = df.pivot_table(values='Sales', index='Region', columns='Product', aggfunc='sum')

pivot_table

Product    A    B    C
Region
East     234  123  789
West     678  456  987

In [5]:
#Problem: Merge two DataFrames, one containing employee details and another containing their department details, on a common key.

# Sample DataFrames
df1 = pd.DataFrame({
    'EmployeeID': [1, 2, 3, 4],
    'EmployeeName': ['John', 'Alice', 'Bob', 'Eve'],
    'DepartmentID': [101, 102, 101, 103]
})

df2 = pd.DataFrame({
    'DepartmentID': [101, 102, 103],
    'DepartmentName': ['HR', 'Finance', 'Engineering']
})

# Merging on 'DepartmentID'
merged_df = pd.merge(df1, df2, on='DepartmentID')

merged_df

   EmployeeID EmployeeName  DepartmentID DepartmentName
0           1         John           101             HR
1           2        Alice           102        Finance
2           3          Bob           101             HR
3           4          Eve           103    Engineering

In [6]:
#Problem: Replace missing values in a DataFrame with the mean of the column.

# Sample DataFrame with missing values
df = pd.DataFrame({
    'A': [1, 2, None, 4, 5],
    'B': [None, 2, 3, None, 5]
})

# Fill missing values with column mean
df_filled = df.fillna(df.mean())

df_filled

     A         B
0  1.0  3.333333
1  2.0  2.000000
2  3.0  3.000000
3  4.0  3.333333
4  5.0  5.000000

In [7]:
#Problem: Suppose you have a DataFrame containing information about products and their prices. 
#Create a new column that categorizes each product as either "Expensive" or "Cheap" based on a threshold price.

# Sample DataFrame
df = pd.DataFrame({
    'Product': ['A', 'B', 'C', 'D', 'E'],
    'Price': [200, 50, 150, 400, 30]
})

# Define the function to categorize products
def categorize(price):
    return 'Expensive' if price > 100 else 'Cheap'

# Apply the function to the 'Price' column
df['Category'] = df['Price'].apply(categorize)

df

  Product  Price   Category
0       A    200  Expensive
1       B     50      Cheap
2       C    150  Expensive
3       D    400  Expensive
4       E     30      Cheap

In [8]:
#Problem: Calculate a rolling average of the last 3 values in a DataFrame containing daily sales data.

# Sample DataFrame
df = pd.DataFrame({
    'Day': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    'Sales': [100, 150, 200, 250, 300]
})

# Calculate the rolling average with a window of 3
df['Rolling_Avg'] = df['Sales'].rolling(window=3).mean()

df

         Day  Sales  Rolling_Avg
0     Monday    100          NaN
1    Tuesday    150          NaN
2  Wednesday    200        150.0
3   Thursday    250        200.0
4     Friday    300        250.0

In [9]:
#Problem: Given a MultiIndex DataFrame, select all the data corresponding to a particular level.

# Sample MultiIndex DataFrame
arrays = [
    ['North', 'North', 'South', 'South', 'East', 'East'],
    ['City A', 'City B', 'City A', 'City B', 'City A', 'City B']
]
index = pd.MultiIndex.from_arrays(arrays, names=('Region', 'City'))
df = pd.DataFrame({'Sales': [234, 678, 123, 456, 789, 987]}, index=index)

# Select all data for the 'South' region
south_region = df.loc['South']

south_region

        Sales
City
City A    123
City B    456

In [10]:
#Problem: Calculate the z-score of sales within each region for a DataFrame with regions and sales data.

# Sample DataFrame
df = pd.DataFrame({
    'Region': ['North', 'North', 'South', 'South', 'East', 'East'],
    'Sales': [234, 678, 123, 456, 789, 987]
})

# Z-score calculation function
def z_score(x):
    return (x - x.mean()) / x.std()

# Apply z-score transformation within each region
df['Z-Score'] = df.groupby('Region')['Sales'].transform(z_score)

df

  Region  Sales   Z-Score
0  North    234 -0.707107
1  North    678  0.707107
2  South    123 -0.707107
3  South    456  0.707107
4   East    789 -0.707107
5   East    987  0.707107

In [11]:
#Problem: Merge two DataFrames on multiple columns and handle cases where there are mismatches in keys.

# Sample DataFrames
df1 = pd.DataFrame({
    'EmployeeID': [1, 2, 3, 4],
    'EmployeeName': ['John', 'Alice', 'Bob', 'Eve'],
    'DepartmentID': [101, 102, 101, 103],
    'LocationID': [1001, 1002, 1001, 1003]
})

df2 = pd.DataFrame({
    'DepartmentID': [101, 102, 104],
    'LocationID': [1001, 1002, 1004],
    'DepartmentName': ['HR', 'Finance', 'Legal']
})

# Merging on 'DepartmentID' and 'LocationID'
merged_df = pd.merge(df1, df2, on=['DepartmentID', 'LocationID'], how='left')

merged_df

   EmployeeID EmployeeName  DepartmentID  LocationID DepartmentName
0           1         John           101        1001             HR
1           2        Alice           102        1002        Finance
2           3          Bob           101        1001             HR
3           4          Eve           103        1003            NaN

In [12]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'Group': ['A', 'A', 'B', 'B'],
    'Value': [10, 20, 30, 40]
})

# Set 'Group' as the index
df.set_index('Group', inplace=True)

# Reset the index without specifying drop (drop=False by default)
result = df.reset_index()

print(result)

  Group  Value
0     A     10
1     A     20
2     B     30
3     B     40

In [13]:
# if you use drop=True
df.reset_index(drop=True)

   Value
0     10
1     20
2     30
3     40

In [14]:
#Problem: Increase the salary of all employees by 10% and return the updated DataFrame.

# Custom function to increase salary

import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'Name': ['John', 'Alice', 'Bob', 'Eve'],
    'Age': [23, 35, 27, 25],
    'Salary': [50000, 80000, 45000, 60000]
})

def increase_salary(salary):
    return salary * 1.10

# Apply the function to the 'Salary' column
df['Updated_Salary'] = df['Salary'].apply(increase_salary)

df

    Name  Age  Salary  Updated_Salary
0   John   23   50000         55000.0
1  Alice   35   80000         88000.0
2    Bob   27   45000         49500.0
3    Eve   25   60000         66000.0

In [15]:
#Problem: Create a pivot table to show the sum of sales for each Product across different Regions.

# Sample DataFrame
sales_df = pd.DataFrame({
    'Region': ['East', 'West', 'East', 'West', 'East'],
    'Product': ['A', 'A', 'B', 'B', 'C'],
    'Sales': [100, 200, 150, 250, 300]
})

# Create a pivot table
pivot_table = sales_df.pivot_table(values='Sales', index='Region', columns='Product', aggfunc='sum')

pivot_table

Product      A      B      C
Region
East     100.0  150.0  300.0
West     200.0  250.0    NaN

In [16]:
#Problem: Merge two DataFrames on a common column EmployeeID.

# Sample DataFrames
df1 = pd.DataFrame({
    'EmployeeID': [1, 2, 3, 4],
    'Name': ['John', 'Alice', 'Bob', 'Eve']
})

df2 = pd.DataFrame({
    'EmployeeID': [1, 2, 3, 5],
    'Department': ['HR', 'Finance', 'Engineering', 'Legal']
})

# Merge DataFrames on 'EmployeeID'
merged_df = pd.merge(df1, df2, on='EmployeeID', how='inner')

merged_df

   EmployeeID   Name   Department
0           1   John           HR
1           2  Alice      Finance
2           3    Bob  Engineering

In [17]:
#Problem: Fill missing values in a DataFrame with the mean of the column.

# Sample DataFrame with missing values
df_with_nan = pd.DataFrame({
    'A': [1, 2, None, 4, 5],
    'B': [None, 2, 3, None, 5]
})

# Fill missing values with column mean
df_filled = df_with_nan.fillna(df_with_nan.mean())

df_filled

     A         B
0  1.0  3.333333
1  2.0  2.000000
2  3.0  3.000000
3  4.0  3.333333
4  5.0  5.000000

In [18]:
#Problem: Select all data corresponding to a particular level in a MultiIndex DataFrame.

# Sample MultiIndex DataFrame
arrays = [
    ['North', 'North', 'South', 'South'],
    ['City A', 'City B', 'City A', 'City B']
]
index = pd.MultiIndex.from_arrays(arrays, names=('Region', 'City'))
df_multi = pd.DataFrame({'Sales': [234, 678, 123, 456]}, index=index)

# Select all data for 'South' region
south_region = df_multi.loc['South']

south_region

        Sales
City
City A    123
City B    456

In [19]:
#Problem: Normalize the Sales column within each Region group by subtracting the mean and dividing by the standard deviation.

# Sample DataFrame
df_group = pd.DataFrame({
    'Region': ['North', 'North', 'South', 'South'],
    'Sales': [100, 200, 150, 250]
})

# Apply z-score transformation within each region
df_group['Z-Score'] = df_group.groupby('Region')['Sales'].transform(lambda x: (x - x.mean()) / x.std())

df_group

  Region  Sales   Z-Score
0  North    100 -0.707107
1  North    200  0.707107
2  South    150 -0.707107
3  South    250  0.707107

In [20]:
import pandas as pd

# Sample DataFrame
df_group = pd.DataFrame({
    'Region': ['North', 'North', 'South', 'South'],
    'Sales': [100, 200, 150, 250]
})

print(df_group)

# Apply z-score transformation within each region
z_scores = df_group.groupby('Region').apply(lambda x: (x['Sales'] - x['Sales'].mean()) / x['Sales'].std())

# Add the z-score column to the original DataFrame
df_group['Z-Score'] = z_scores.reset_index(drop=True)

print(df_group)

  Region  Sales
0  North    100
1  North    200
2  South    150
3  South    250
  Region  Sales   Z-Score
0  North    100 -0.707107
1  North    200  0.707107
2  South    150 -0.707107
3  South    250  0.707107

C:\Users\SAIKAT MUKHERJEE\AppData\Local\Temp\ipykernel_7476\3238828325.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  z_scores = df_group.groupby('Region').apply(lambda x: (x['Sales'] - x['Sales'].mean()) / x['Sales'].std())

In [21]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Calculate the sum across columns for each row
df['Row_Sum'] = df.sum(axis=1)

print(df)

   A  B  C  Row_Sum
0  1  4  7       12
1  2  5  8       15
2  3  6  9       18

In [22]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Use apply with axis=1 to sum columns A, B, and C row-wise
df['Row_Sum'] = df.apply(lambda row: row['A'] + row['B'] + row['C'], axis=1)

print(df)

   A  B  C  Row_Sum
0  1  4  7       12
1  2  5  8       15
2  3  6  9       18

In [23]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Column-wise summation
column_sums = df.sum(axis=0)

print(column_sums)

A     6
B    15
C    24
dtype: int64

In [24]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Calculate the sum for each column and append it as a new row
print(df.sum())
df.loc['Total'] = df.sum()

print(df)

A     6
B    15
C    24
dtype: int64
       A   B   C
0      1   4   7
1      2   5   8
2      3   6   9
Total  6  15  24

In [25]:
#Problem: Given a DataFrame with a column of email addresses, extract the domain name (e.g., gmail.com) and 
#create a new column with this information.

import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'Email': ['john.doe@gmail.com', 'alice@yahoo.com', 'bob.smith@outlook.com', 'eve@company.co']
})

# Extract domain using regex
df['Domain'] = df['Email'].str.extract(r'@([\w\.-]+)')

print(df)

                   Email       Domain
0     john.doe@gmail.com    gmail.com
1        alice@yahoo.com    yahoo.com
2  bob.smith@outlook.com  outlook.com
3         eve@company.co   company.co

In [26]:
#Problem: You have a DataFrame with phone numbers, and you want to identify which phone numbers match a specific pattern (e.g., XXX-XXX-XXXX).

# Sample DataFrame
df = pd.DataFrame({
    'PhoneNumber': ['123-456-7890', '987 654 3210', '1234567890', '(123)-456-7890', '123.456.7890']
})

print(df)


# Check if phone numbers match the pattern (XXX-XXX-XXXX)
df['Valid_Phone'] = df['PhoneNumber'].str.match(r'^\d{3}[-]\d{3}[-]\d{4}$')

print(df)

      PhoneNumber
0    123-456-7890
1    987 654 3210
2      1234567890
3  (123)-456-7890
4    123.456.7890
      PhoneNumber  Valid_Phone
0    123-456-7890         True
1    987 654 3210        False
2      1234567890        False
3  (123)-456-7890        False
4    123.456.7890        False

In [27]:
#Problem: Extract all capitalized words from a column of text and store them in a new column.

# Sample DataFrame
df = pd.DataFrame({
    'Text': ['John Doe is a Data Scientist', 'Alice is an Engineer at Google', 'Bob works at IBM']
})

print(df)

# Extract all capitalized words using regex
df['Capitalized_Words'] = df['Text'].str.findall(r'\b[A-Z][a-z]*\b')

print(df)

                             Text
0    John Doe is a Data Scientist
1  Alice is an Engineer at Google
2                Bob works at IBM
                             Text             Capitalized_Words
0    John Doe is a Data Scientist  [John, Doe, Data, Scientist]
1  Alice is an Engineer at Google     [Alice, Engineer, Google]
2                Bob works at IBM                         [Bob]

In [28]:
#Problem: Replace occurrences of multiple patterns in a column of text with a specified value.

# Sample DataFrame
df = pd.DataFrame({
    'Text': ['I like apples', 'I dislike bananas', 'I love cherries', 'I hate durians']
})

print(df)


# Replace 'dislike' and 'hate' with 'neutral'
df['Modified_Text'] = df['Text'].str.replace(r'dislike|hate', 'neutral', regex=True)

print(df)

                Text
0      I like apples
1  I dislike bananas
2    I love cherries
3     I hate durians
                Text      Modified_Text
0      I like apples      I like apples
1  I dislike bananas  I neutral bananas
2    I love cherries    I love cherries
3     I hate durians  I neutral durians

In [29]:
#Problem: Identify rows where the text starts and ends with a vowel.

# Sample DataFrame
df = pd.DataFrame({
    'Text': ['apple', 'banana', 'orange', 'umbrella', 'grape', 'kiwi']
})

print(df)

# Find strings that start and end with a vowel
df['Starts_Ends_Vowel'] = df['Text'].str.match(r'^[aeiouAEIOU].*[aeiouAEIOU]$')

print(df)


#Note:

'''
The . and * are distinct components of a regular expression, and they serve different purposes when combined. Let's break down the difference between using .* and using * alone.

What Does * Alone Mean?
The * symbol in a regular expression means "zero or more" of the preceding element. However, * must always follow a character, pattern, or character class to define what should be matched zero or more times.

a*: This means "zero or more a characters." It will match an empty string, "a", "aa", "aaa", and so on.
What Does . Mean?
The . (dot) in a regular expression matches any single character except a newline.

.: This matches exactly one character of any type (except a newline).
What Does .* Mean?
When you combine . and *, you get .*, which means "zero or more of any character."

.*: This will match any sequence of characters, including an empty sequence. It is used to match any string of characters between other specified patterns in a regex.
Why You Need Both . and *
If you used * by itself, without a preceding element, it wouldn't make sense in the context of a regular expression because * needs something to quantify. The * alone can't be used because it must be preceded by something that defines what should be repeated zero or more times.

Example with .*:
Consider the regex pattern ^[aeiouAEIOU].*[aeiouAEIOU]$:

[aeiouAEIOU]: Matches the first character as a vowel.
.*: Matches zero or more of any character(s) in between the first and last vowel.
[aeiouAEIOU]$: Matches the last character as a vowel.
This pattern will match strings like:

"apple"
"umbrella"
"AeIOU"
"a"
Example without .* (using * alone):
If you tried to use * alone, like this: ^[aeiouAEIOU]*[aeiouAEIOU]$, you would get a pattern that:

[aeiouAEIOU]*: Matches zero or more vowels at the start of the string.
[aeiouAEIOU]$: Matches a single vowel at the end of the string.
This pattern would match:

"a"
"aeiou"
"ai"
But it would not match:

"apple" (because ppl are not vowels and there's no .* to allow for these non-vowel characters in the middle).

Summary:
.*: This combination is necessary to match "zero or more of any character," allowing flexibility in matching any characters (or no characters) between specified patterns.
* alone: Cannot be used by itself; it needs a preceding character or pattern to define what should be matched zero or more times.
Thus, .* is essential when you need to allow for any characters to appear between the start and end patterns you're matching, like in the case of finding strings that start and end with a vowel.

'''

       Text
0     apple
1    banana
2    orange
3  umbrella
4     grape
5      kiwi
       Text  Starts_Ends_Vowel
0     apple               True
1    banana              False
2    orange               True
3  umbrella               True
4     grape              False
5      kiwi              False

'\nThe . and * are distinct components of a regular expression, and they serve different purposes when combined. Let\'s break down the difference between using .* and using * alone.\n\nWhat Does * Alone Mean?\nThe * symbol in a regular expression means "zero or more" of the preceding element. However, * must always follow a character, pattern, or character class to define what should be matched zero or more times.\n\na*: This means "zero or more a characters." It will match an empty string, "a", "aa", "aaa", and so on.\nWhat Does . Mean?\nThe . (dot) in a regular expression matches any single character except a newline.\n\n.: This matches exactly one character of any type (except a newline).\nWhat Does .* Mean?\nWhen you combine . and *, you get .*, which means "zero or more of any character."\n\n.*: This will match any sequence of characters, including an empty sequence. It is used to match any string of characters between other specified patterns in a regex.\nWhy You Need Both . and *\nIf you used * by itself, without a preceding element, it wouldn\'t make sense in the context of a regular expression because * needs something to quantify. The * alone can\'t be used because it must be preceded by something that defines what should be repeated zero or more times.\n\nExample with .*:\nConsider the regex pattern ^[aeiouAEIOU].*[aeiouAEIOU]$:\n\n[aeiouAEIOU]: Matches the first character as a vowel.\n.*: Matches zero or more of any character(s) in between the first and last vowel.\n[aeiouAEIOU]$: Matches the last character as a vowel.\nThis pattern will match strings like:\n\n"apple"\n"umbrella"\n"AeIOU"\n"a"\nExample without .* (using * alone):\nIf you tried to use * alone, like this: ^[aeiouAEIOU]*[aeiouAEIOU]$, you would get a pattern that:\n\n[aeiouAEIOU]*: Matches zero or more vowels at the start of the string.\n[aeiouAEIOU]$: Matches a single vowel at the end of the string.\nThis pattern would match:\n\n"a"\n"aeiou"\n"ai"\nBut it would not match:\n\n"apple" (because ppl are not vowels and there\'s no .* to allow for these non-vowel characters in the middle).\n\nSummary:\n.*: This combination is necessary to match "zero or more of any character," allowing flexibility in matching any characters (or no characters) between specified patterns.\n* alone: Cannot be used by itself; it needs a preceding character or pattern to define what should be matched zero or more times.\nThus, .* is essential when you need to allow for any characters to appear between the start and end patterns you\'re matching, like in the case of finding strings that start and end with a vowel.\n\n'

# Few more RegEx

In [5]:
import re

text = "Python is a popular Language created by Guido van Rossum"
pattern = r'\b[A-Z][a-z]*\b'
result = re.findall(pattern, text)
print(result)  # Output: ['Python', 'Language', 'Guido', 'Rossum']

['Python', 'Language', 'Guido', 'Rossum']

In [12]:
import re

email = "example.email@domain.com"
pattern = r'^[a-zA-Z0-9.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
result = re.match(pattern, email)
print(bool(result))  # Output: True
print(result)

True
<re.Match object; span=(0, 24), match='example.email@domain.com'>

In [9]:
import re

email = "example.email@domain.com"
pattern = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
result=re.findall(pattern,email)
result

['example.email@domain.com']

In [13]:
import re

date = "2023-08-10"
pattern = r'\b\d{4}-\d{2}-\d{2}\b'
result = re.match(pattern, date)
print(bool(result))  # Output: True

True

In [16]:
import re

text = "The price is 45 dollars, and the discount is 10%"

pattern=r'[\d{1}]+'
print(re.findall(pattern,text))

['45', '10']

In [17]:
import re

text = "The price is 45 dollars, and the discount is 10%"
pattern = r'\d+'
result = re.findall(pattern, text)
print(result)  # Output: ['45', '10']

['45', '10']

In [20]:
import re

text = "This   is   a  test    string"
pattern = r'\s+'
result = re.sub(pattern, ' ', text)
print(result)  # Output: "This is a test string"

This is a test string

In [21]:
import re

text = "abc def ghi jkl mno"
pattern = r'\b\w{3}\b'
result = re.findall(pattern, text)
print(result)  # Output: ['abc', 'def', 'ghi', 'jkl', 'mno']

['abc', 'def', 'ghi', 'jkl', 'mno']

In [22]:
import re

text = "Python3"
pattern = r'^\w+$'
result = re.match(pattern, text)
print(bool(result))  # Output: True

True

In [23]:
import re

urls = "Visit https://www.example.com or http://another-example.org"
pattern = r'https?://(www\.)?([\w-]+)\.[\w.-]+'
result = re.findall(pattern, urls)
domains = [domain[1] for domain in result]
print(domains)  # Output: ['example', 'another-example']

['example', 'another-example']

In [28]:
string_sample="Visit https://www.example.com or http://another-example.org"
for i in re.findall(r'https?:\/\/(www\.)?([\w-]+)\.[\w.-]+',string_sample):
    print(i[1])

example
another-example

In [32]:
import re

text = 'He said, "Hello" and then "Goodbye"'
pattern = r'"([^"]*)"'
result = re.findall(pattern, text)
print(result)  # Output: ['Hello', 'Goodbye']

['Hello', 'Goodbye']

In [34]:
class MyClass:
    def instance_method(self):
        return "This is an instance method"

# Creating an instance of MyClass
#print(MyClass.instance_method())
obj = MyClass()
print(obj.instance_method())  # Output: "This is an instance method"

# Trying to call the instance method without instantiating
# This will raise a TypeError because `self` is not provided.
# print(MyClass.instance_method())

This is an instance method

In [35]:
# Define a list
my_list = [1, 2, 3, 4, 2, 2, 5, 2, 6]

# Use count() to find the frequency of the value 2
frequency = my_list.count(2)

# Print the result
print(f"The frequency of 2 in the list is: {frequency}")

The frequency of 2 in the list is: 4

In [36]:
max(my_list)

6

In [37]:
pp=[9,3,1,5,6]
pp.sort(reverse=True)

In [38]:
pp

[9, 6, 5, 3, 1]